from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STUDENT_RESOURCE = ROOT / "student_resource"
DATASET_DIR = STUDENT_RESOURCE / "dataset"
TRAIN_DIR = DATASET_DIR / "train"
TEST_DIR = DATASET_DIR / "test"
OUTPUT_DIR = ROOT / "output"
TRAIN_CANDIDATE_PATH = OUTPUT_DIR / "candidate_pairs.tsv"
BLOCKING_CACHE_DIR = OUTPUT_DIR / "cache" / "blocking"
BLOCKING_CACHE_VERSION = 1
EDA_CHUNK_SIZE = 100_000
MAX_BLOCK_POSTINGS = 200
MIN_TOKEN_LENGTH = 4
MAX_CANDIDATES_PER_ENTITY = 500
NAME_NGRAM_SIZE = 4
MIN_NAME_NGRAM_LENGTH = 6
BLOCKING_BATCH_SIZE = 25_000
BLOCKING_MATCH_BATCH_SIZE = 1_000
BLOCKING_INSERT_BATCH_SIZE = 50_000

MODEL_TYPE = "lightgbm"
BLOCKING_STRATEGIES = ["name", "phonetic", "tokenset", "address"]
THRESHOLD_TAU = 0.5
MARGIN = 0.1
